# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message_scroll_label.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("*{\n"
"      background-color: #313338;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setStyleSheet("*{\n"
"   background-color: #313338;\n"
"\n"
"}\n"
"QAbstractScrollArea{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 280))
        self.scrollAreaWidgetContents.setStyleSheet(" *{\n"
"    background-color: #313338;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.message_viewer_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.message_viewer_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #313338;")
        self.message_viewer_label.setText("")
        self.message_viewer_label.setObjectName("message_viewer_label")
        self.gridLayout_2.addWidget(self.message_viewer_label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        # Form.setWindowFlags(Qt.FramelessWindowHint)

